org.gradle.jvmargs=-Xmx1536m -Dfile.encoding=UTF-8 -Duser.language=en -Duser.country=US

systemProp.user.language=en
systemProp.user.country=US

android.useAndroidX=true
android.enableJetifier=true
android.nonTransitiveRClass=true

android.overridePathCheck=true

androidide.logsender.isEnabled=false